### ISSUE TITLE
IndexSizeError: Index or size is negative or greater than the allowed amount

### ISSUE THREAD

**Issue by luanribeirosv** [zxing-js/library#156]
Hi.

In Firefox, when you start the QR Code reader with an external webcam, this error occurs:

`IndexSizeError: Index or size is negative or greater than the allowed amount`

The test was performed on the demo page itself: [https://zxing-js.github.io/library/examples/qr-camera/](https://zxing-js.github.io/library/examples/qr-camera/)

Library version: 0.12.3
Firefox version: 66.0.3
Webcam: Logitech c270

**Comment by alperendev98** [comment]
I got same error

**Comment by luanribeirosv** [comment]
Now in the version 0.14.2 library is always happening error when starting the camera and with any camera.

**Comment by odahcam** [comment]
Have you tested in Chrome? (https://zxing-js.github.io/library/examples/multi-camera/)

**Comment by luanribeirosv** [comment]
In chrome I've already tested it and it's working. But in Firefox the error continues.

**Comment by 0ndorio** [comment]
The issue here is a race condition which for some reasons mostly appears in Firefox but not in Chrome.

It appears because the attributes `videoWidth` and `videoHeight` of the video element are not yet initialized when `createCaptureCanvas` is called the first time which results in a canvas element with a size of 0 and therefore triggers the mentioned `IndexSizeException` shortly afterwards.

During debugging you will recognize that as soon as you introduce a break point or another timeout a few lines before the attributes are actually accessed the error disappears magically. 

The underlying cause seems to be hidden somewhere inside the logic of `playVideoOnLoadAsync`, `playVideoOnLoad` and `tryPlayVideo` as the try to use event handler to react on the video loading process to ensure that promise of `playVideoOnLoadAsync` is only resolved as soon as the video element is ready for action. If this would work properly the meta information should always be present in `createCaptureCanvas` as the necessary event `loadedmetadata` should always appear in front of `canplay` [1].

[1] https://www.w3schools.com/tags/av_event_loadedmetadata.asp
