### ISSUE TITLE
Barcode scanner doesn't detect by mobile browser

### ISSUE THREAD

**Issue by arjunkgit** [zxing-js/library#18]
Hi, I have tried online version of barcode scanner but which doesn't work by mobile browser from mobile device. Even I tried with laptop camera, it opens here but doesn't capture any code. 

I'm looking on browser based scanner with Javascript. Please let me know if you are facing the same issue.

URL : https://aleris.github.io/zxing-typescript/examples/qr-camera/

**Comment by odahcam** [comment]
This is our base fork's example, it doesn't support 1D barcodes if that's what you are looking for.

Our latest published version supports only QR codes, but it's working fine.

Barcodes will be published in the next release, because they have no docs nor examples yet. 😢 

If you wanna see our scanner in action, here's the link: https://zxing-js.github.io/ngx-scanner/

As I said we aren't scanning 1D codes yet, I believe that in +-1 month they will be fully released. 🙂

**Comment by arjunkgit** [comment]
Thank you for your response !  Yes, I was looking for 1D support.

So as you mentioned in future release we may see the working version of 1D.

**Comment by odahcam** [comment]
Closing as we now have some 1D support and more comming.
