### ISSUE TITLE
can't enumerate devices, method not supported

### ISSUE THREAD

**Issue by ismailjamil22** [zxing-js/library#225]
can't enumerate devices, method not supported

**Comment by amedeekirk** [comment]
Having similar issue. To go into more detail, I am attempting to use the listVideoInputDevices method on a laptop with a webcam. The example on the website seems to work, but after fiddling around and trying to glean some info from that source code and the readme, I'm still having problems. Any ideas/need more information from my end?

Thanks!

**Comment by odahcam** [comment]
For hosting under IPv4 you need SSL, also you need to provide more info or this issue will be closed. Thanks.

**Comment by rame0** [comment]
I had the same issue under HTTP protocol. Switching to HTTPS helped to solve this.
Looks like Chrome (may be others too) blocking some features when using unencrypted connection.

**Comment by lucassusanto** [comment]
@ismailjamil22 Hello, I ran into the same problem and I think what's causing the problem is this code `if (!this.canEnumerateDevices) throw new Error("Can't enumerate devices, method not supported.");`

The following code is `navigator.mediaDevices.enumerateDevices()` which retrieves the list of available devices. In this case, `navigator.mediaDevices` might be `undefined`. According to [this](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia), it is `undefined` because the document isn't loaded securely.

So, there's a chance that the url you are using is not https. I am developing in localhost and it is not complaining.

**Comment by odahcam** [comment]
Exactly @lucassusanto , the browser requests SSL for accessing the WebRTL features (which include device's media devices). But there's an exception for localhost, so developers can develop easily w/o having to issue a certificate for development environments. If you do try to serve your application under IPv4 (IP server), you gonna need SSL even if it's hosted on your local machine.

**Comment by dvodvo** [comment]
I realize this issue is closed, but the ReadMe should state that the `the browser requests SSL` even for the concompassing page, but allows for exceptions on localhost.

Frankly, in some cases the script would run (up to identifying devices), but not 'activate' a device and thus camera would not be accessible (or ask browser for access).  Maybe there was some wonky cache.  Still...

A bit of a gotcha.

**Comment by mertuarez** [comment]
Works only on https. There should be check when is not secure that this commant id not supported for HTTP.
