### ISSUE TITLE
Version 0.17.x not yet available via NPM

### ISSUE THREAD

**Issue by igregson** [zxing-js/library#301]
Seeing the "experimental" bit regarding the repo now using GitHub Actions to publish to NPM in [the release notes](https://github.com/zxing-js/library/releases/tag/v0.17.0) suggests the issue is there.

**Comment by odahcam** [comment]
Wow you are fast! I'm very aware as you can see:

![image](https://user-images.githubusercontent.com/3942006/81353797-6d3b6e80-90a0-11ea-98b2-38b9bc665126.png)

The reason why this is not on NPM yet is that we have a test called `QRCodeBlackBox.2` that is not passing and I'm trying to fix it before follow with the Action fix. 

The problem with the Action execution was the outdated lockfile due to the recent merge, it was with the same problem in the source branch and it became a problem again in the base (master) branch. I could re-publish the Release so the Action would run again, but the tests will fail and the package will not be published again. As I have the test working on Windows I thought I could take a look in the Linux issue (I'm not so sure at this point hehe, this is an odd bug, but I'll try a little more). If I can't solve this in an hour I will ignore this test and re-run the Action.

**Comment by odahcam** [comment]
It was fixed, but I couldn't figure out how to make GITHUB_TOKEN work, I even struggled to login in the GitHub package registry manually in my machine.
