### ISSUE TITLE
Try Harder

### ISSUE THREAD

**Issue by EvilDonkey** [zxing-js/library#303]
Hey,
Thanks for zxing, love it.

I am having problems with try harder (or I have misunderstood something). I was under the impression that setting TryHarder would enable scans from 0 to 360 degrees. However, it seems to only work on 0, 90, 180 and 360 degrees. If I hold the phone at 45 degrees, it doesnt find the barcode.

I am using Ionic 5 and v0.17.0.

            const hints = new Map();
            const formats = [BarcodeFormat.CODE_128, BarcodeFormat.EAN_8, BarcodeFormat.EAN_13];
            hints.set(DecodeHintType.POSSIBLE_FORMATS, formats);
            hints.set(DecodeHintType.TRY_HARDER, true);

            const codeReader = new BrowserMultiFormatReader(hints);
            const result = await codeReader.decodeFromImageUrl(imageSrcData);

Any way I can enable full 360 degrees scanning?

**Comment by odahcam** [comment]
Thanks for the love.

> Any way I can enable full 360 degrees scanning?

While I'm pretty sure you can use the library to implement every angle scan yourself, I would say **do not do this** for you own sake. JS is already slow for 0, 90, 180 and 360, I can't imagine how bad can it be with full 360 scan.

Unfortunately the library won't be able to decode properly sometimes, that's expected, but in zero and 360 angles there's a chance the lib will detect the code sometimes until I'd say 40 degrees. Perhaps just implementing decode attempts in more angles will solve your problem, like instead of trying to decode in 4 angles, trying in these 4 angles intersections: 45º, 135º and 215º.

If, for some reason, you really wanna do this, we can follow up and implement some custom scanner together, but at least for browser usage I'd not recommend.
