### ISSUE TITLE
Unable to import the library

### ISSUE THREAD

**Issue by MastroLindus** [zxing-js/library#71]
Hi,

I have installed the library through npm, and now I am trying to import the library in a typescript project by importing the ES6 module:
```import { BrowserQRCodeReader, Result } from "@zxing/library";```

Typescript compiles my code correctly, but apparently the library doesn't get imported.
At runtime I get a console error in the browser that the module is not found:
Uncaught Error: Cannot find module '@zxing/library'.

**Comment by odahcam** [comment]
I can't reproduce that error, what version are you using?

**Comment by odahcam** [comment]
Sometimes these error occours due to mismatch between the project's TS version and IDE TS version, where our IDE is unable to check if the package really exists.

Just to show how odd this issue is, here's a print of `ngx-scanner` dev code which I'm using in production:

![image](https://user-images.githubusercontent.com/3942006/43031211-6d0ce4ee-8c73-11e8-88ae-64d491d117db.png)

As you can see, I have no import errors. 😕

**Comment by MastroLindus** [comment]
@odahcam Hi, and first of all, thank you for your answer.

The problem I had was not that I couldn't compile the code in typescript, both the ide and the project build were not showing errors. The problem I saw was that at runtime I could see an error in the console stating that the @zxing/library module could not be found.

For 2 hours I tried to fix it without success, until I decided to switch to a different library that worked.

Today I tried again to install the library and use it, in order to give you more hints for this issue, and everything works fine...
Apologies, I must have had some issue with my dev environment, or the build tool i use (Meteor) maybe did something funky.

Anyway, I cannot reproduce it so I am going to close the issue.
The library looks really nice by the way, keep up the good work!

**Comment by odahcam** [comment]
Thanks @MastroLindus! Feel free to open new issues if ou want. 😉

**Comment by abidhkm** [comment]
I am getting the same error.. opened as an issue. any help is appreciated

**Comment by avensiafresch** [comment]
I struggled all day with this as well but I think I found the solution; it's because the default moduleResolution is `classic`, which doesn't find the deeper index.d.ts. 

In your `tsconfig.json` add this:

```
"compilerOptions": {
    ...otherStuff,
    "moduleResolution": "node",
}
```

**Comment by odahcam** [comment]
You shouldn't compile the TypeScript, but use the JS distribution files instead. If you think there's a another issue, please file one with useful debugging information here at the repo. Thanks.

**Comment by avensiafresch** [comment]
Oh, how would you go about to configure that..? Mark it as `external` in webpack, add it as a <script> tag & then import it in your files - sort of like you do with React?

**Comment by odahcam** [comment]
Yes it does, the package comes with typings so it can be interpreted gracefully in TypeScript projects. The only problem here is if your project is a TypeScript project and if it's configured to load node_modules's packages. Since I cannot understand exactly what's your problem I'd like to request a demo so we can figure out a solution for your case.
